### ISSUE TITLE
soshelp command doesn't work and crashes in LLDB 3.9

### ISSUE THREAD

**Issue by micli** [dotnet/coreclr#12851]
**Environment**:
```
$ dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

```
**Description**:
I can load libsosplugin.so successfully and I can view help information by help but not soshelp. Below are repo steps:
```
parallels@ubuntu:~$ whereis dotnet
dotnet: /usr/bin/dotnet /usr/share/dotnet /usr/share/man/man1/dotnet.1.gz
parallels@ubuntu:~$ cd /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/
parallels@ubuntu:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01$ lldb-3.9
(lldb) plugin load libsosplugin.so
(lldb) soshelp
(lldb) soshelp pe
Segmentation fault (core dumped)
parallels@ubuntu:/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01$ 

```
When I input soshelp, it echoed nothing. When I input soshelp with any .NET Core extension command like dumpheap or pe, it was crashed. The same issues exists on Debian 8 with LLDB 3.9 either. But it works fine on CentOS 7 with lldb 3.6.

**Comment by janvorli** [comment]
@mikem8361 - I don't remember if we have succeeded making the libsosplugin.so that we distribute work for newer lldb versions than 3.6. I think you've said it was working for you after the change that you've made about a month ago, but I am not sure.
@micli, if you can build coreclr repo with lldb-dev for lldb-3.9 installed, it should produce libsosplugin.so that should work fine with lldb-3.9. The https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md has instructions on how to do that - just use the deb packages source settings for lldb 3.9 that are described there as arm specific.

**Comment by mikem8361** [comment]
I haven’t got the libsosplugin.so we distribute building/working with lldb 3.9 yet. It got sidetracked by other changes.

**Comment by micli** [comment]
I did submitted an issue a month before https://github.com/dotnet/coreclr/issues/12098
After that @mikem8361 did some changes in CMakeList.txt  and then I found libsosplugin.so could be loaded by LLDB 3.9.  I thought it has been resolved. But it seems it only can be loaded but no one command works correctly.

```
parallels@debian-gnu-linux-8:~$ ls
code     Documents  Downloads        Music     Public     Videos
Desktop  dotnet     dump1.5731.5731  Pictures  Templates
parallels@debian-gnu-linux-8:~$ whereis dotnet
dotnet: /usr/local/bin/dotnet
parallels@debian-gnu-linux-8:~$ lldb-3.9
(lldb) plugin load /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libsosplugin.so
(lldb) clrstack
(lldb) dumpheap
(lldb) help
```

**Comment by mikem8361** [comment]
There are still problems loading a libsosplugin.so built for lldb 3.6 (like in our official builds) but loading it under lldb 3.9.  I still have a work item to get our official (portable) builds to build against 3.9.  It should make for 2.1.

**Comment by mikem8361** [comment]
We now build the libsosplugin.so on Linux for lldb 3.9 (in the master branch .NET Core 2.1).

**Comment by sherlock1982** [comment]
I don't really understand why it's closed. It's still crashing the same way with 3.9. 
I'm using version 2.0.3. Is there a way to resolve it?

**Comment by micli** [comment]
@sherlock1982
I know you situation. But only .Net Core 2.1.x support LLDB 3.9. With app under.Net Core 2.0.3, you have to use LLDB 3.6.

**Comment by micli** [comment]
I have already compiled libsosplugin.so for LLDB 3.9. If you want to debug.Net Core 2.0.3 apps by LLDB 3.9,please download my proper debugging plugin at: https://github.com/micli/netcoredebugging/tree/master/Linux.x64.SOS.3.9
Sorry about any typo due to I logged words on mobile phone.

**Comment by sherlock1982** [comment]
Yes with this plugin now it works, thanks a lot. 
Are there any plans to include it into 2.0.x branch? 
Also I downloaded the latest build of 2.1 and plugin bundled there still not working.
