### ISSUE TITLE
Segmentation fault during GC when running on ARM

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/coreclr#13500]
I've ported my ASP.NET Core application to netcoreapp2.0 (it works with net462 and Mono), publish it with `-c Release -f netcoreapp2.0 -r linux-arm` on Windows, copy it to my Linux box (Yocto Linux, Kernel 4.9, Freescale/NXP/Qualcomm i.MX6 SoloX, ARMv7) and start it using the executable `./My.App`.

I can see my application starting up and printing some messages, I sometimes even get to do some HTTP requests, but sooner or later it dies with a Segmentation Fault. I've been running within gdb and there, I get varying stack traces:

```
[...]
Application started. Press Ctrl+C to shut down.

Thread 8 "My.App" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 3999]
0xb681e1ea in SVR::gc_heap::mark_object_simple1(unsigned char*, unsigned char*, int) () from /root/my-app/libcoreclr.so
```
or
```
Thread 1 "My.App" received signal SIGSEGV, Segmentation fault.
0xa8aa79f8 in ?? ()
```
or
```
Thread 15 "My.App" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 4210]
0xb66ff9da in JIT_ChkCastClassSpecial_Portable ()
   from /root/my-app/libcoreclr.so
```

**Comment by Tragetaschen** [comment]
Hmm, strange: I have rebuilt my Linux image to include the glibc debugging symbols and `libthread_db[.so.1|-1.0.so]`. Now, it doesn't crash anymore.

**Comment by Tragetaschen** [comment]
It seems the non-crash was luck. It reproduces most of the time with the `mark_object_simple1` stack trace. 

I've been able to compile the v2.0.0 tags of coreclr, corefx and core-setup with a non-release build of coreclr and get this stack trace:
```
(gdb) bt
#0  0xb6232eee in MethodTable::GetBaseSize (this=0x0)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/methodtable.h:1795
#1  0xb66238a6 in SVR::my_get_size (ob=0x9d76f7cc)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:8988
#2  0xb65f1e0a in SVR::gc_heap::mark_object_simple1 (this=0x12a378,
    oo=0x9aab3f64 "\315\223\232\247\025\001",
    start=0x9aab3f64 "\315\223\232\247\025\001", thread=0)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:17823
#3  0xb65f2e5e in SVR::gc_heap::mark_object_simple (this=0x12a378,
    po=0xacc45d18, thread=0)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:18267
#4  0xb662eb62 in SVR::gc_heap::mark_through_cards_helper (this=0x12a378,
    poo=0xacc45d18, n_gen=@0xacb2f61c: 42, cg_pointers_found=@0xacb2f624: 0,
    fn=
    (void (SVR::gc_heap::*)(SVR::gc_heap * const, uint8_t **, int)) 0xb65f2b2d <SVR::gc_heap::mark_object_simple(unsigned char**, int)>,
    nhigh=0x9e6d8000 "", next_boundary=0x9a6d9000 "\350p\006")
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:27714
#5  0xb65f903c in SVR::gc_heap::mark_through_cards_for_segments (
    this=0x12a378, fn=
    (void (SVR::gc_heap::*)(SVR::gc_heap * const, uint8_t **, int)) 0xb65f2b2d <SVR::gc_heap::mark_object_simple(unsigned char**, int)>, relocating=0)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:28021
#6  0xb65e0a54 in SVR::gc_heap::mark_phase (this=0x12a378,
    condemned_gen_number=1, mark_only_p=0)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:19769
#7  0xb65d8922 in SVR::gc_heap::gc1 (this=0x12a378)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:15381
#8  0xb65bc85a in SVR::gc_heap::garbage_collect (this=0x12a378, n=1)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:16946
#9  0xb65bb19c in SVR::gc_heap::gc_thread_function (this=0x12a378)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:5298
#10 0xb65bad98 in SVR::gc_heap::gc_thread_stub (arg=0x12a378)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:25001
#11 0xb670d65a in GCThreadStub (param=0x12eea8)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcenv.os.cpp:609
#12 0xb68d6366 in CorUnix::CPalThread::ThreadEntry (pvParam=0x12eeb8)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/pal/src/thread/thread.cpp:1749
#13 0xb6f97f0c in start_thread (arg=0xacb30450)
    at /usr/src/debug/glibc/2.25-r0/git/nptl/pthread_create.c:458
#14 0xb6d2fdf8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76
   from /lib/libc.so.6
```

**Comment by Tragetaschen** [comment]
I've also done a non-stripped release build where the two top functions of the call stack seem to be inlined. I think, I've got all the necessary tools available, but I wouldn't know how to start.

```
(gdb) bt
#0  SVR::gc_heap::mark_object_simple1 (this=0x10e920, oo=<optimized out>, start=<optimized out>, thread=<optimized out>)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:17734
#1  0xb689acb6 in SVR::gc_heap::mark_object_simple (this=0x10e920, po=<optimized out>, thread=<optimized out>)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:18267
#2  0xb689d3ca in SVR::GCHeap::Promote (ppObject=0xaa2d8a30, sc=0xad02fcfc, flags=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:33971
#3  0xb67d81d8 in GcInfoDecoder::EnumerateLiveSlots (this=0xad02f114, pRD=<optimized out>,
    reportScratchSlots=<error reading variable: access outside bounds of object referenced via synthetic pointer>, inputFlags=<optimized out>,
    pCallBack=<optimized out>, hCallBack=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcinfodecoder.cpp:934
#4  0xb66c9aca in EECodeManager::EnumGcRefs (this=<optimized out>, pRD=0xad02f690, pCodeInfo=0xad02f5b8, flags=0, pCallBack=<optimized out>,
    hCallBack=<optimized out>, relOffsetOverride=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/eetwain.cpp:5043
#5  0xb6767c1c in GcStackCrawlCallBack (pCF=0xad02f398, pData=0xad02fc6c) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcenv.ee.cpp:332
#6  0xb6713f48 in Thread::MakeStackwalkerCallback (this=0x1df880, pCF=0xad02f398, pCallback=0xb6767a59 <GcStackCrawlCallBack(CrawlFrame*, void*)>,
    pData=0xad02fc6c) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/stackwalk.cpp:868
#7  0xb67140dc in Thread::StackWalkFramesEx (this=0x1df880, pRD=0xad02f690, pCallback=0xb6767a59 <GcStackCrawlCallBack(CrawlFrame*, void*)>,
    pData=0xad02fc6c, flags=34048, pStartFrame=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/stackwalk.cpp:949
#8  0xb6714376 in Thread::StackWalkFrames (this=0x1df880, pCallback=0xb6767a59 <GcStackCrawlCallBack(CrawlFrame*, void*)>, pData=0xad02fc6c, flags=34048,
    pStartFrame=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/stackwalk.cpp:1032
#9  0xb67680ee in ScanStackRoots (pThread=0x1df880, fn=0xb689d269 <SVR::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, sc=0xad02fcfc)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcenv.ee.cpp:564
#10 0xb6767f52 in GCToEEInterface::GcScanRoots (fn=0xb689d269 <SVR::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, condemned=<optimized out>,
    max_gen=<optimized out>, sc=0xad02fcfc) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcenv.ee.cpp:593
#11 0xb68945a8 in SVR::gc_heap::mark_phase (this=0x10e920, condemned_gen_number=2, mark_only_p=<optimized out>)
    at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:19694
#12 0xb689219c in SVR::gc_heap::gc1 (this=0x10e920) at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:15381
#13 0xb68881d0 in SVR::gc_heap::garbage_collect (this=<optimized out>, n=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:16932
#14 0xb68872dc in SVR::gc_heap::gc_thread_function (this=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:5298
#15 0xb6887112 in SVR::gc_heap::gc_thread_stub (arg=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/gc/gc.cpp:25001
#16 0xb6907bc8 in GCThreadStub (param=<optimized out>) at /usr/src/debug/coreclr/2.0.0-r0/git/src/vm/gcenv.os.cpp:609
#17 0xb69bf1fe in CorUnix::CPalThread::ThreadEntry (pvParam=0x112e00) at /usr/src/debug/coreclr/2.0.0-r0/git/src/pal/src/thread/thread.cpp:1749
#18 0xb6f97f0c in start_thread (arg=0xad030450) at /usr/src/debug/glibc/2.25-r0/git/nptl/pthread_create.c:458
#19 0xb6d2fdf8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by swgillespie** [comment]
Unfortunately this is a pretty general call stack indicating that the heap has gotten corrupted in some way, which can happen for a lot of reasons. Can you use LLDB and SOS to run the `sos VerifyHeap` command when you see the SEGV?

**Comment by Tragetaschen** [comment]
What is CoreCLR's behavior when the system runs out of memory on linux(-arm)?

Background: I had a little misconfiguration on my embedded measurement hardware: Our FPGA writes into a DMA ring buffer, the .NET core application `mmap`s that memory and copies the data into `new`ed arrays for further processing. However, the input data rate was too high for the processing to catch up and so the `net462` build running on Mono slowly fills up the instrument's memory until eventually the kernel's OOM killer does its job.

I tried lldb, but it fails to start. I need to dig in a little further.

**Comment by RussKeldorph** [comment]
I assume the original issue is resolved.  Changed to `area-PAL` due to the open question about OOM on Linux/ARM.  Please close if/when there is no further action to be taken on this issue.

**Comment by BruceForstall** [comment]
I'm going to close this issue.

Suggestion: if a GC or memory issue still exists, try .NET Core 2.1 -- quite a lot of GC and memory issues have been fixed in 2.1 for ARM.
