### ISSUE TITLE
Debug failed with c++ hosting

### ISSUE THREAD

**Issue by amos402** [dotnet/coreclr#16776]
![default](https://user-images.githubusercontent.com/3406561/37035459-96cb3fa8-2187-11e8-94d8-2151115a486c.png)
I set the host's debugger type to `Mixed` for start and get this error.
Use attach for debugging was success.

**Comment by jkotas** [comment]
@amos402 Thank you for reporting this issue. What is the .NET Core build that you are hitting this on?

We had a bug in Mixed mode debugging that was fixed recently https://github.com/dotnet/coreclr/pull/16552 .

cc @mikem8361

**Comment by amos402** [comment]
2.0.5

**Comment by amos402** [comment]
I had try it on `2.1.0-preview1`, the problem still exist.
Visual Studio: 15.6.0

**Comment by mikem8361** [comment]
The mixed mode debugging fix didn't make into preview1, but there should be any problems with 2.0.5. I need more details on how you launched (or attached) the debugging and the C++ host you are using.

Thanks.

**Comment by amos402** [comment]
The host just like this (https://github.com/dotnet/docs/tree/master/samples/core/hosting) and startup from C++ project.
![default](https://user-images.githubusercontent.com/3406561/37069166-23a8c52a-21ed-11e8-8645-08a5e77dbb38.png)

**Comment by mikem8361** [comment]
This is fixed in the latest master branch build which you can get here: https://github.com/dotnet/core-setup#daily-builds (2.1.0-preview3-26319-04).

**Comment by mikem8361** [comment]
@amos402, it looks like you will also need VS 15.7 Preview 1 for mixed mode just-in-time debugging to work from here: https://www.visualstudio.com/vs/preview/

**Comment by amos402** [comment]
I have tried that, VS 15.7 Preview 1 just with same error.

**Comment by mikem8361** [comment]
Sorry about all the back and forward but I want to be clear: did you try VS 15.7 Preview 1 and the 2.1.0-preview3-26319-04 version of the runtime?

There were two problems that needed to be fixed: one in VS and one in coreclr.

**Comment by amos402** [comment]
@mikem8361 Yes, I'm sure about that.
![default](https://user-images.githubusercontent.com/3406561/37746591-f43a7aca-2db5-11e8-9f2e-52c449d8fc66.png)
![default](https://user-images.githubusercontent.com/3406561/37746595-f943dba6-2db5-11e8-8030-9515b0c6a0b4.png)
![asd](https://user-images.githubusercontent.com/3406561/37746796-e67340ec-2db6-11e8-9bc6-66e592894e6d.gif)

**Comment by gregg-miskelly** [comment]
That is the error that the project system is telling the debugger to launch for Desktop (Full Framework) .NET debugging.

I don’t think you can do .NET Core mixed mode debugging from a .vcxproj. You need to instead configure a .NET Core project to launch an external program, and enable mixed mode debugging from there.

**Comment by amos402** [comment]
@gregg-miskelly Yes, that may work. But it would lost break point before the runtimeHost call Start. So there's no way to startup from a vcxproj for now?

**Comment by gregg-miskelly** [comment]
I should add that to enable unmanaged code debugging in the .NET Core project, you will want to open \<projectDir\>\Properties\launchSettings.json, and set the [`nativeDebugging`](https://github.com/dotnet/project-system/blob/492dac929d5d31b3bb6ab67caf2c1b6e8bf56cfa/src/ProjectSystemSetup/Properties/launchSettings.json#L22) property to `true`.

**Comment by gregg-miskelly** [comment]
Yes, interop debugging is .NET Core has the restriction that you cannot hit breakpoints in native code before the .NET runtime starts. 

@mikem8361 is there an issue that tracks removing that restriction?

Fixing this would require a major architectural change to how interop debugging works, so I don't think it will be resolved any time soon. I would probably recomend switching back and forth between your C++ project and your .NET Core project depending on which type of code you want to debug. This is what I do all the time while debugging the .NET Core debugger (which has lots of both C# and C++ code).

**Comment by mikem8361** [comment]
I created issue #17153 to track this, but like Gregg said this is a major change that will not be in 2.x.
