### ISSUE TITLE
Coreclr build failure after #20286

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#20320]
We are getting the following error in the coreclr builds on the perf runs after #20286 was checked in.

`C:\j\w\perf_perflab_---22877dc9\Tools\tests.targets(132,112): error MSB4066: The attribute "DestinationName" in element <SupplementalTestData> is unrecognized. [C:\j\w\perf_perflab_---22877dc9\tests\src\baseservices\compilerservices\RuntimeWrappedException\RuntimeWrappedException.csproj]`

**Comment by adiaaida** [comment]
@ViktorHofer Let me know if you need a perfsnake machine to repro this on. I am wondering if there is something wrong with how the machines are configured, given this passed the smoketests.

**Comment by fiigii** [comment]
I also see this build failure with VS2015.

**Comment by ViktorHofer** [comment]
That was already fixed with a buildtools update which came in 10h ago.

**Comment by adiaaida** [comment]
@ViktorHofer do you know when we will actually see the fix from buildtools in coreclr? We are still seeing this failure.
