### ISSUE TITLE
Segmentation fault on Linux with .Net Core 3.0 preview2

### ISSUE THREAD

**Issue by sunnycase** [dotnet/coreclr#22828]
Reference: https://github.com/SixLabors/ImageSharp/issues/844

### Description
Resize a image from 320x240 to 128x128 cause segmentation fault on Ubuntu. It runs fine on Windows.
And I have tested it using .Net Core 2.0, it runs fine on Ubuntu and Windows.

### Steps to Reproduce
1. Clone this repo: https://github.com/sunnycase/imagesharp-issue
2. Run dotnet publish -c Release -r linux-x64
3. cd to bin/Release/linux-x64/publish
4. Run `./imagesharp-issue`

### System Configuration
Ubuntu 18.04 on WSL

- ImageSharp version: 1.0.0-beta0006
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Ubuntu 18.04 on WSL
- .NET Framework version: dotnet core 3.0 preview2
- Additional information:

Code backup
```c#
using (var image = Image.Load<Rgb24>(typeof(Program).Assembly.GetManifestResourceStream("imagesharp_issue.0.jpg")))
{
    image.Mutate(x =>
        x.Resize(128, 128));
}
```

**Comment by tactical-drone** [comment]
I am also getting random core dumps with `.Net Core 3.0 preview2`.

I am very glad to see someone else is getting it too because I have spent 2 days tracking this crash and I cannot find the cause. In Windows Subsystem for Linux the app does not exit with `SIGSEGV` but rather becomes unresponsive to `SIGTERM` and flatlines two cores. On native linux I get return `errno 139`.

The interesting part in my case is it happens often shortly after the app starts, or rarely at all later on. Like once i 5 hours. My app uses `unsafe` and `interop`.

Hope that helps.

**Comment by janvorli** [comment]
@sunnycase I've tried to repro it on my native Ubuntu 16.04 and it doesn't crash. Have you only tested in on the WSL or on a Linux VM / native box?
I am going to try it on Ubuntu 18.04 VM too.

**Comment by janvorli** [comment]
I can confirm that it crashes on Ubuntu 18.04 VM.

**Comment by janvorli** [comment]
Actually, it crashes on Ubuntu 16.04 with the preview2 too. I was testing it with the latest version of .NET core 3.0 built from the master branch and the issue is gone.

So it is an issue that's already fixed in the master and so the next release of .NET Core 3.0 preview should work fine for you. @sunnycase you can also use the latest version built from master that you can get here if you want to get it work: https://github.com/dotnet/core-sdk.

**Comment by tactical-drone** [comment]
I have been building https://github.com/dotnet/cli/pull/10795 but it has not worked. The problem remains.

@janvorli Can you please explain to me how you made that build? I would love to get my hands on it because I still wonder maybe this is not why mine is crashing. It could still be a bug in my system since I am using `interop`.

**Comment by janvorli** [comment]
You can download the binaries, you don't have to build it yourself. Here are the steps that I've followed to try to repro the issue with the latest SDK:
```sh
cd ~
mkdir dotnet3.0-latest
cd dotnet3.0-latest
wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz
tar -xf dotnet-sdk-latest-linux-x64.tar.gz
rm dotnet-sdk-latest-linux-x64.tar.gz
cd ~
git clone 1. https://github.com/sunnycase/imagesharp-issue
cd imagesharp-issue
~/dotnet3.0-latest/dotnet publish -c Release -r linux-x64
./bin/Release/netcoreapp3.0/linux-x64/publish/imagesharp-issue
```

**Comment by sunnycase** [comment]
@janvorli I have tested using the latest SDK and the issue is gone. Thank you for your help!

**Comment by 0xd4d** [comment]
@sunnycase Could you test this with tiering disabled: `COMPlus_TieredCompilation=0`
