### ISSUE TITLE
Registration Free Com Interop

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#23963]
Hi All,
I apologize in advance if this is not the right place to ask this kind of question.

I am using the Microsoft Office COM interop (Microsoft.Office.Interop.Word and Microsoft.Office.Interop.Outlook)

Often times customers have COM registry settings that aren't quite correct and it causes type mismatches when working with instances of the classes.

According to this article:
https://docs.microsoft.com/en-us/dotnet/framework/interop/registration-free-com-interop

It appears as though it is possible to tell my application not to use the registry to lookup COM information/types but I can't figure out how to do that with the assemblies above.  Does anyone have any examples they can post?

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@TonyValenti Great question. I have several interop examples in a repo https://github.com/AaronRobinsonMSFT/COMInterop.

Do you have a specific example of an issue you are hitting with respect to Office COM Interop?

**Comment by TonyValenti** [comment]
@AaronRobinsonMSFT - Thanks for the help!
Here's an example coming from a client machine:
References:
````
Microsoft.Office.Interop.Word
````

Code:
````
namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {

            var App = new Microsoft.Office.Interop.Word.Application();
            App.ShowMe();

        }
    }
}
````

Error:
````
System.InvalidCastException: 'Unable to cast COM object of type 'Microsoft.Office.Interop.Word.ApplicationClass' to interface type 'Microsoft.Office.Interop.Word._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00020970-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).'
````

I notice that when I try to run the example, my reference to Microsoft.Office.Interop.Word also gets redirected to the GAC which I don't want.

Thoughts?

**Comment by AaronRobinsonMSFT** [comment]
@TonyValenti This kind of issue was addressed by [Type equivalence and embedded interop types](https://docs.microsoft.com/dotnet/framework/interop/type-equivalence-and-embedded-interop-types). A [video for Visual Studio 2010](https://channel9.msdn.com/Blogs/kmcgrath/Embedding-Type-Information-from-Microsoft-Office-Assemblies) also talks about how to enable the feature - the details still apply.

For Office there is also a [.NET Core example](https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo) that is almost identical to a .NET Framework project.

**Comment by TonyValenti** [comment]
@AaronRobinsonMSFT I watched the video and it sounds like all I need to do is turn on "Embed Interop Types", however, I did that on the machine I'm getting teh error from and I still get that error.  Any suggestions?

**Comment by AaronRobinsonMSFT** [comment]
@TonyValenti That really should work. Please try the following [demo](https://support.microsoft.com/en-us/help/302084/how-to-automate-microsoft-excel-from-microsoft-visual-c-net) and see if the same problem is observed.

**Comment by TonyValenti** [comment]
Hi @AaronRobinsonMSFT -
Thanks so much for the suggested demo but that isn't helping.  I've created a sample project:
https://github.com/TonyValenti/OutlookCom

That shows the challenge I'm running into.  It seems as though whatever I do, the calls are trying to be redirected to a newer version of a GAC assembly.  How do I force calls to GetActiveObject to use the information in one of the PIA assemblies included with my app?

Also - related to this issue, I have approval to compensate the person who helps us resolve this issue.  If we need to set up a time for a screen share or such, I can be reached at Tony.Valenti@FasterLaw.com .

**Comment by AaronRobinsonMSFT** [comment]
@TonyValenti I will reach out to you offline, but for the sake of the community I want to provide some minor insight here. The [`Marshall.GetActiveObject()`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.getactiveobject) API is a convenience function for the [`GetActiveObject()`](https://docs.microsoft.com/windows/desktop/api/oleauto/nf-oleauto-getactiveobject) Win32 OLE API. The function will always query the Running Object Table, which means whatever is registered there will be what is loaded. In this case, the type being activated isn't defined by you, but rather by Office and their CoClass that is being activated must be the one that is registered.

I admit I could be missing some thing here so I will reach out to you offline.
