### ISSUE TITLE
stdlib symbols exported by dotnet

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#25494]
We have reproduced strange application crash on Linux CoreCLR. We have native library, which is loaded in CoreClr application and called though PInvoke (and create it's own unmanged threads). To be clear, it is really CoreCLR profiler (and was loaded as profiler), but crash happens outside of any profiler calls/callbacks, so I believe it can be ignored that it is also profiler.
Application crashes with invalid pointer similar to:
```
*** Error in `dotnet': munmap_chunk(): invalid pointer: 0x00007f8e4809aae0 ***
```

We have two different (but similar) stack traces, that result to crash:
```
#0: 0x00007f0f82fa6fff libc.so.6`gsignal + 207
#1: 0x00007f0f82fa842a libc.so.6`abort + 362
#2: 0x00007f0f82fe4c00 libc.so.6`??? + 704
#3: 0x00007f0f82feafc6 libc.so.6`??? + 166
#4: 0x00007f0f82feb80e libc.so.6`??? + 286
#5: 0x000000000040fd10 dotnet`__gnu_cxx::new_allocator<std::__detail::_Hash_node_base*>::deallocate(std::__detail::_Hash_node_base**, unsigned long) + 32
#6: 0x000000000040fb9e dotnet`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_deallocate_buckets(std::__detail::_Hash_node_base**, unsigned long) + 78
#7: 0x00007f0f7956769c libprofiler.so`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_deallocate_buckets(this=0x00007f0a567fa118) + 28
#8: 0x00007f0f795675c2 libprofiler.so`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable(this=0x00007f0a567fa118) + 34
#9: 0x00007f0f795673a5 libprofiler.so`std::unordered_map<std::string, std::vector<std::string, std::allocator<std::string> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > >::~unordered_map(this=0x00007f0a567fa118) + 21
#10: 0x00007f0f79564bc3 libprofiler.so`SomeClass::~SomeClass(this=...) + 35

#0: 0x00007f51d52dffff libc.so.6`gsignal + 207
#1: 0x00007f51d52e142a libc.so.6`abort + 362
#2: 0x00007f51d531dc00 libc.so.6`??? + 704
#3: 0x00007f51d5323fc6 libc.so.6`??? + 166
#4: 0x000000000040fd10 dotnet`__gnu_cxx::new_allocator<std::__detail::_Hash_node_base*>::deallocate(std::__detail::_Hash_node_base**, unsigned long) + 32
#5: 0x000000000040fb9e dotnet`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_deallocate_buckets(std::__detail::_Hash_node_base**, unsigned long) + 78
#6: 0x000000000040f9ff dotnet`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash_aux(unsigned long, std::integral_constant<bool, true>) + 335
#7: 0x000000000040f688 dotnet`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&) + 40
#8: 0x000000000040f022 dotnet`std::_Hashtable<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, true>*) + 146
#9: 0x000000000040edd8 dotnet`std::__detail::_Map_base<std::string, std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > >, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::string const&) + 184
#10: 0x000000000040e198 dotnet`std::unordered_map<std::string, std::vector<std::string, std::allocator<std::string> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > >::operator[](std::string const&) + 40
#11: 0x00007f51c2d6ae78 libprofiler.so`SomeClass::someOperation(this=..., arg1=..., arg2=...) + 40
```
(I have removed any our library specific names from last stack frame). Looks like crash is reproducible only with some level of load - but with load it happens in minute or so.

If we look on stack frames, we may notice, that call was transferred from our library to dotnet executable. Looks like both we and dotnet use `std::unordered_map<std::string, std::vector<std::string>>`, and with ELF symbol interposition we used implementation from dotnet ELF, instead of our library and something was incompatible on this path.
To test it, I've re-linked our library with `-Wl,--exclude-libs,ALL` option and was not able to reproduce an issue within 20 minutes of load.

Should CLR also hide stdlib symbols from dotnet ELF export table?

We have reproduced issue on CoreCLR 2.2.

**Comment by iskiselev** [comment]
Should other CoreCLR libraries that will be loaded in process before user managed libraries also prevent exporting such symbols? Not sure if not doing it may result in similar problem. (I'm even not sure that we correctly identified problem).

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/core-setup/pull/3769

**Comment by iskiselev** [comment]
I'm not sure if issue was fully resolved or not, I see much less symbols defined on dotnet 3.0 nigthly docker, but I still see next lines:
```
0000000000408030  w   DF .text  000000000000028b  Base        void std::vector<std::string, std::allocator<std::string> >::_M_emplace_back_aux<std::string const&>(std::string const&)
000000000040b370  w   DF .text  0000000000000155  Base        std::string __gnu_cxx::__to_xstring<std::string, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...)
```
It can be checked with `objdump -C -T dotnet`.
I don't know if it may break anything or not.

Version info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012650
 Commit:    b959696aad

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview7-012650/

Host (useful for support):
  Version: 3.0.0-preview7-27826-04
  Commit:  5c4d829254

.NET Core SDKs installed:
  3.0.100-preview7-012650 [/usr/share/dotnet/sdk]
```
