### ISSUE TITLE
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25810]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190721.1/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.GCTests~2FGetGCMemoryInfo

**Log:**
```
Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: -1844674407689672704
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 35

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
```

**Comment by danmosemsft** [comment]
#24414

@maoni0

**Comment by Maoni0** [comment]
@VSadov would you please take a look?

**Comment by VSadov** [comment]
#24414 was a test issue and should be fixed.

This looks like a new failure. Here the API seems to return a bogus result.

**Comment by VSadov** [comment]
We did not have any changes around this API, except https://github.com/dotnet/coreclr/pull/25724

@cshung can you take a quick look if the change could cause this? 
It looks like we get negative memory size on ARM32

**Comment by ViktorHofer** [comment]
Still happening on corefx: https://dnceng.visualstudio.com/public/_build/results?buildId=302066&view=ms.vss-test-web.build-test-results-tab&runId=8594366&resultId=167836&paneView=debug

Will disable the test again.

**Comment by sergiy-k** [comment]
@cshung, did you have a chance to look at this failure and check whether it is related to your change?

**Comment by cshung** [comment]
I didn't. I was told this is a low priority bug, after all, it only repros on Linux ARM32.

Earlier I fixed a compiler warning related to integer overflow and discovered that the `CGroup` could return bogus value as `PhysicalMemoryLimit` and `RestrictedPhysicalMemoryLimit`. IMHO, that looks like a kernel/docker bug. In particular, the values read from the files are larger than `size_t::max()`, which is simply impossible.

The original code ignored the compiler warning, so the value probably got wrapped and passed the test. My new value clipped it to `size_t::max()`, which is probably the best I could have done the preserve the meaning [basically I am saying the PhysicalMemoryLimit and RestrictedPhysicalMemoryLimit is as much as the system could have].

I doubt somewhere the number got marshaled to managed code as a signed integer. If we know where that spot is, we can try to do the same clipping there. Of course, the bug could be completely unrelated, this is just my suspicion. 

Is it a priority to fix this?

**Comment by sergiy-k** [comment]
I would like to understand whether we have to fix this issue in 3.1

**Comment by cshung** [comment]
Does the bug repro in 3.0? I thought the change was introduced after it.

**Comment by sergiy-k** [comment]
Oh, never mind. I'm sorry for the confusion. For some reason I thought that the change was merged in June instead of July. So it is not high priority but I would like have it fixed relatively soon (in a few weeks) in order to avoid accumulating test bugs.

**Comment by ViktorHofer** [comment]
With how many iterations did you test? If less than 1k I would try it again with that number. Some flaky tests are hard to reproduce.

**Comment by hoyosjs** [comment]
I did 10k, no negative numbers. Don't know what the lab setup is to see if it's related.

**Comment by sergiy-k** [comment]
Is it possible to get a crash dump from the lab?

**Comment by ViktorHofer** [comment]
There were no crashes, the negative number was just reported as an xunit assertexception.

**Comment by sergiy-k** [comment]
It will be very hard to get to the bottom of this issue without a crash dump given that the problem does not reproduce on local machines. We need to make the test generate a dump file when it fails. How do we do it?
It would be very cool if Xunit could be configured to generate a crush dump if an assert fails (maybe based on an attribute that we can set on demand).

**Comment by ViktorHofer** [comment]
> It would be very cool if Xunit could be configured to generate a crush dump if an assert fails (maybe based on an attribute that we can set on demand).

@bradwilson @onovotny is that somehow possible?

**Comment by stephentoub** [comment]
You could Environment.FailFast instead of Assert.Whatever.
